### PR TITLE
Adding Images folder

### PR DESCRIPTION
**Pull request by renatabg2205**
ERD image and wine and weather sample data output

### CODE REVIEW

**Comment by renatabg2205** [comment]
Added Images folder with ERD image, wine sample and weather sample outputs. Added Resources folder with wine and weather dataset sample

**Comment by renatabg2205** [comment]
wine_pyspark.ipynb loads data from US_wine_dataset.csv and US_AL_cseat13t19.csv in S3 and stores them in RDS.

**Review by secicciari — COMMENTED** [review]
looks good!

**Review by secicciari — COMMENTED** [review]
looks good!

**Review by secicciari — COMMENTED** [review]
looks good!

**Review by katief01 — APPROVED** [review]
Looks great!

**Pull request merged**
